### PR TITLE
Bug fix: uninitialized padding eliminated

### PR DESCRIPTION
**Pull request by Lurker00**
See the description and the proof of the bug here: https://github.com/Lurker00/byedpi/commit/e02ce91363bb4b7b312168d3db3a21bd5140cdd3#r146761416

`_Static_assert` is a GCC extension that exists since version 4.6. I added it to ensure there are no uninitialized bytes in between.

Alternatively, you can use `memset(&key, 0, sizeof(key))` before first use, but it is slower.

I didn't try to build for Windows though. If MSVC is used, `#include <stddef.h>` may be required.

### CODE REVIEW

**Comment by hufrea** [comment]
Damn, I just posted a release.

**Comment by Lurker00** [comment]
Sorry, I thought my comments to your commit I made a day ago would be enough to bring your attention... The release was unexpected, and I immediately made the formal test and then this PR.

**Comment by hufrea** [comment]
You left a comment on your fork, I didn't receive a notification. but ok, maybe more bugs will be discovered, tomorrow 14.1 will be released.

**Comment by dartvader316** [comment]
Struct padding is a compiler optimization feature and does not need a fix. 
Also struct packing is not portable across compilers and also can introduce big safety problems with memory.

**Comment by hufrea** [comment]
The problem is that this structure is copied as is. this structure is compared to others on a byte-by-byte basis using memcmp. The data in the placeholder can be anything even after initialization; this is undefined behavior.

**Comment by dartvader316** [comment]
Yes, you need to initialize struct with zeroes before using.
But packing and manual padding (and compiler can still possible add padding for some architectures) is not a good solution.

**Comment by Lurker00** [comment]
@dartvader316 There were two problems here: the struct is used as a byte sequence, presuming the sequence contains a port and an address, but:
1. It contained padding bytes with random data, and
2. It didn't contain the full address.

Meaning, it didn't meet the goal.

Yes, the most portable solution is to `memset` with 0 before the first use _**and**_ use `offsetof` for the length of the part before the address(es). Or, use a "serializer", like some other languages do (even less effective by both speed and memory).

> compiler can still possible add padding for some architectures

Yes. But my code is protected by `_Static_assert`. The compiler will not build possibly wrong code. So, while it may look not portable, it is fast and error proof, and binary portable (i.e. the output binary, _if any_, is correct).

**Comment by dartvader316** [comment]
> byte-by-byte basis using memcmp

Comparing struct with memcmp also is not recommended as i know. The most safe way is to compare struct fields manually. Yes, this is will look bad but i don't know a better safer way.

**Comment by Lurker00** [comment]
Just in case:
> This probably can be done with `key = {0};`

While most of compilers optimize it into zeroing the whole struct, it is not mandatory, and, as such, paddings still may have random values. And you never mentioned the bug with calculation of the byte sequence length ;)

**Comment by hufrea** [comment]
> But packing and manual padding (and compiler can still possible add padding for some architectures) is not a good solution.

I agree to use memset and remove pack. But note that it is already used here:
https://github.com/hufrea/byedpi/blob/a9ecc83932543c6a22984b168a77543490763e89/proxy.h#L27

> Comparing struct with memcmp also is not recommended as i know. The most safe way is to compare struct fields manually. 

The code uses a common wrapper over the AVL tree, it is used for both hosts and IP, so will have to change a lot.

**Comment by dartvader316** [comment]
> it is fast and error proof

Actually struct padding optimization was added to speed up memory addressing. So forcing packed struct will make it slower.

> While most of compilers optimize it into zeroing the whole struct, it is not mandatory,

I think zeroing the whole struct is mandatory before using. It can work now because of this only zeroing  padding  workaround but can break later with structure fields changes .

> Yes. But my code is protected by `_Static_assert`

`_Static_assert` is also c11 feature. It is probably also part of gnu c so you don't get warnings about this. This can break building on BSD systems. Haven't tested yet thought.

> The code uses a common wrapper over the AVL tree, it is used for both hosts and IP, so will have to change a lot.

Yes, it has problems. Would be good to fix that but i we can at least make sure that structs are properly fully set to zero before using.

>  #pragma pack(push, 1) 

Yes, this also problematic. If you don't believe me, you can read this:
https://devblogs.microsoft.com/oldnewthing/20200103-00/?p=103290

Also as i know there is no fully compiler portable way to declare a packed struct. But from my old tests even `tcc` compiled this project without problems.

---

Anyway, if you sure that you tested this with many architectures with something like clang sanitizers or valgrind to make sure there is no memory problems we can keep this as it is.

**Comment by dartvader316** [comment]
Sorry if i look so intrusive, i just want to reduce possible memory safety problems.

**Comment by hufrea** [comment]
> Sorry if i look so intrusive

it’s very good that you are so attentive to everything, it’s very useful, thank you.

**Pull request merged**
